# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13yJSFNO7h5DRtpjJzsUXOegetBt1I6ay
"""

from google.colab import drive
drive.mount('/content/drive')

"""TASK-1
IRIS FLOWER CLASSIFICATION
"""

path='/content/iris.data'

import pandas as pd
df=pd.read_csv("/content/iris.data")
df.head()

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# Features and target
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Report
print(classification_report(y_test, y_pred))

"""The analysis showed that machine learning can effectively classify Iris flowers into different species using their sepal and petal measurements.

The Iris dataset was successfully loaded and analyzed
using Python and Scikit-learn.
A classification model was trained to identify the three flower species: Iris-setosa, Iris-versicolor, and Iris-virginica.
The model was evaluated using test data and achieved an accuracy of 90%.
The classification report indicated good precision, recall, and F1-scores for most flower classes.
The results demonstrate that machine learning algorithms can accurately predict flower species based on their physical characteristics.
Overall, this project helped in understanding basic machine learning concepts such as data preprocessing, model training, prediction, and performance evaluation using classification techniques.




"""